# version: "3.8"
# services:
#   backend:
#     build:
#       context: .
#       dockerfile: Dockerfile.backend
#     volumes:
#       - ./backend/:/usr/src/app/
#     ports:
#       - 5000:5000
#     environment:
#       PORT: 5000
#       FLASK_DEBUG: 1
#     image: react-flask-app-api
#   client:
#     build:
#       context: .
#       dockerfile: Dockerfile.client
#     # volumes:
#     #   - ./client/:/app
#     #   - /app/node_modules
#     ports:
#       - 3000:3000
#     image: react-flask-app-client
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    image: react-flask-app-api
    ports:
      - 5000:5000
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: react-flask-app-client
    ports:
      - "3000:80"
